```{r}
library("dplyr")
data("AustralianElectionPolling", package = "pscl")
glimpse(AustralianElectionPolling)
```

Unique polling organizations (Morgan face-to-face and phone polls treated separately):
```{r}
AustralianElectionPolling %>% group_by(org) %>% tally()
```

- date of poll is the median day (rounded down) for when they are in the field.

```{r}
aus_elections <-
  bind_rows(
    data_frame(date = as.Date("2004-10-09"), ALP = 37.6, sd = .00025),
    data_frame(date = as.Date("2007-11-24"), ALP = 43.4, sd = .00025)
  )

aus_polling <-
  AustralianElectionPolling %>%
  group_by(org, startDate, endDate) %>%
  # There are two Nielson polls on 2007-11-19 to 21.
  summarize(ALP = weighted.mean(ALP, sampleSize),
            sampleSize = sum(sampleSize)) %>%
  ungroup() %>%
  mutate(date = floor_date(as.Date(startDate) + difftime(endDate, startDate, unit = "days"), unit = "day"),
         y = ALP / 100,
         sd = sqrt(y * (1 - y) / sampleSize),
         org = as.character(org)) %>%
  select(date, org, y, sd) %>%
  bind_rows(select(mutate(elections, y = ALP / 100, org = "Election"), -ALP)) %>%
  mutate(time = as.integer(difftime(date, as.Date("2004-10-09"), unit = "days")) + 1)

datelist <-
  data_frame(date = seq(min(aus_polling[["date"]]), max(aus_polling[["date"]]), by = "days"),
             time = min(aus_polling[["time"]]):max(aus_polling[["time"]]))

polling_values <-
  aus_polling %>%
  select(date, time, org, y) %>%
  spread(org, y) %>%
  full_join(select(datelist, date), by = "date") %>%
  arrange(date) %>%
  select(-time)

polling_sd <-
  aus_polling %>%
  select(date, time, org, sd) %>%
  spread(org, sd) %>%
  full_join(select(datelist, date), by = c("date")) %>%
  arrange(date) %>%  
  select(-time)

ssm_process_na <- function(x) {
  nonmiss <- !is.na(x)
  num_nonmiss <- apply(nonmiss, 1, function(.x) sum(.x))
  idx_nonmiss <- t(apply(nonmiss, 1, function(.x) {
    idx <- which(.x)
    c(idx, rep(0, length(.x) - length(idx)))
  }))
  list(n = num_nonmiss, idx = idx_nonmiss)
}

aus_elec_data <-
  within(list(), {
    y <- as.matrix(select(polling_values, -date))
    missing <- ssm_process_na(y)
    p_t <- missing$n
    y_idx <- missing$idx
    rm(missing)
    y[is.na(y)] <- 0
    n <- nrow(y)
    p <- ncol(y)
    sigma_eps <- as.matrix(select(polling_sd, -date)) %>%
      apply(2, function(.) if_else(is.na(.), median(., na.rm = TRUE), .))
    sigma_delta <- .0075 # prior on house effects. p. 479. Jackman text.
    zeta <- 0.1
    a1 <- array(0.5)
    P1 <- matrix(0.25, 1, 1)
  })

```

```{r}
polling_mod <- ssm_stan_model("polling1.stan")
polling_samples <- sampling(polling_mod, data = aus_elec_data, iter = 2000, chains = 1,
                            init = list(list(delta = rep(0, aus_elec_data[["p"]] - 1),
                                              sigma_eta = 0.005,
                                             labmda = rep(1 / aus_elec_data[["n"]], aus_elec_data[["n"]]))))
polling_summary <- tidy_stan_summary(summary(polling_samples))
```

```{r}
ggplot(aus_polling, aes(x = date, y = y,
                        ymin = y - 2 * sd,
                        ymax = y + 2 * sd,
                        colour = org)) +
  geom_pointrange()
```

```{r capm-state-plot}
polling_samples <- polling_summary[["all"]] %>%
  left_join(datelist, by = c("dim_1" = "time"))

ggplot() +
  geom_ribbon(data = filter(polling_samples, parameter == "alpha"),
              aes(x = date, ymin = mean - 2 * sd, ymax = mean + 2 * sd), alpha = 0.3) +
  geom_line(data = filter(polling_samples, parameter == "alpha"),
            aes(x = date, y = mean)) +
  geom_point(data = aus_polling, aes(x = date, y = y, colour = org)) +
  theme_minimal()
```

```{r}
filter(polling_summary[["all"]], parameter == "delta") %>%
  select(parname, mean, se_mean, `2.5%`, `97.5%`, n_eff, Rhat)
```



